### PR TITLE
Update Project!

### PR DESCRIPTION
**Pull request by scrapes**
Thanks for the Work! I see a ton of work you put into the project!

### CODE REVIEW

**Comment by fridtjof** [comment]
Awesome, I hope it is just as useful to you as it has been for me :)

**Comment by scrapes** [comment]
> Awesome, I hope it is just as useful to you as it has been for me :)

I recently moved so i have to move my Servers but it has been really usefull for me and i am glad i could start something at least used by 3 People 👍 

I will be more active on GitHub from now on, i see you are planning to implement the virtual devices applet into the Projects, would be super useful but it will only work on Windows and Linux due to the libarys. i think they also need a complete rework but thats really alot of work!

If you have new changes feel free to make Merge Requests!

**Comment by scrapes** [comment]
I especially love commit ecfb25b181008237847d39adebbbcd80b0cf431e

**Comment by fridtjof** [comment]
> i see you are planning to implement the virtual devices applet into the Projects, would be super useful but it will only work on Windows and Linux due to the libarys. i think they also need a complete rework but thats really alot of work!

Actually, those libraries are only needed for passing through your physical devices to the server.

I was planning to just remove that functionality, because IMO there is not much use to it nowadays - if you ever wanted to remote-attach a physical CD for example, you could also just quickly make an ISO file of it.

**Pull request merged**
